spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_batch
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  batch:
    jdbc:
      initialize-schema: always

...